spring:
  thymeleaf:
    mode: HTML
  profiles:
    active: dev
  mvc:
    static-path-pattern: /static/**
  web:
    resources:
      static-locations: classpath:/web/,classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/